export interface IngressNginxSiteInput {
  host: string
  port: number
  isTunnel: boolean
  hasSSL: boolean
}

/** Renders a single nginx server block for one ingress domain. */
export function ingressRenderNginxSite(input: IngressNginxSiteInput): string {
  const effective: IngressNginxSiteInput = input.isTunnel ? { ...input, hasSSL: false } : input
  const header = `# ${effective.host}.conf — generated by jib, do not edit\n`
  return header + httpServer(effective) + (effective.hasSSL ? httpsServer(effective) : '')
}

function proxyLocation(port: number): string {
  return `    location / {
        proxy_pass http://127.0.0.1:${port};
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
`
}

function httpServer(input: IngressNginxSiteInput): string {
  const acme = input.isTunnel
    ? ''
    : `
    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
    }
`
  const body = input.hasSSL
    ? `
    location / {
        return 301 https://$host$request_uri;
    }
`
    : `\n${proxyLocation(input.port)}`
  return `server {
    listen 80;
    listen [::]:80;
    server_name ${input.host};
${acme}${body}}
`
}

function httpsServer(input: IngressNginxSiteInput): string {
  return `
server {
    listen 443 ssl;
    listen [::]:443 ssl;
    server_name ${input.host};

    ssl_certificate     /etc/letsencrypt/live/${input.host}/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/${input.host}/privkey.pem;

    add_header Strict-Transport-Security "max-age=31536000; includeSubDomains" always;
    add_header X-Frame-Options "SAMEORIGIN" always;
    add_header X-Content-Type-Options "nosniff" always;

${proxyLocation(input.port)}}
`
}

/** Returns the managed nginx filename for one host. */
export function ingressNginxConfFilename(host: string): string {
  return `${host}.conf`
}

/** Returns the managed nginx directory for one app. */
export function ingressNginxAppConfDir(nginxDir: string, app: string): string {
  return `${nginxDir}/${app}`
}
