export { default as manifest } from './manifest.ts'
export { default as cli, githubCmd } from './cmd/index.ts'
export { type AuthResult, appPemPath, applyAuth, refreshAuth } from './auth.ts'
export { httpsCloneURL, sshCloneURL } from './remote-url.ts'
export { deployKeyPaths, generateDeployKey } from './keygen.ts'
export { addGitHubAppSource, addGitHubKeySource } from './config-edit.ts'
export { setup, setupDeployKey, setupGitHubApp } from './setup.ts'
