export { default as manifest } from './manifest.ts'
export { default as cli } from './cli.ts'
export { type AuthResult, applyAuth, refreshAuth } from './auth.ts'
export { httpsCloneURL, sshCloneURL } from './remote-url.ts'
export { deployKeyPaths, generateDeployKey } from './keygen.ts'
export { addKeyProvider } from './config-edit.ts'
