import { mkdir, writeFile } from 'node:fs/promises'
import { join } from 'node:path'
import { Document, Scalar, YAMLSeq } from 'yaml'

/** One `host:container` port pair for a service's `ports:` list. */
export interface PortMapping {
  host: number
  container: number
}

/** Input shape for `buildOverride`: per-service labels + optional port list. */
export interface OverrideService {
  name: string
  /** Extra ports to publish. Emitted with YAML `!override` to replace the
   * user's `ports:` list (requires Docker Compose 2.24+). */
  ports?: PortMapping[]
}

export interface OverrideFile {
  services: Record<
    string,
    {
      labels: Record<string, string>
      restart: string
      logging: { driver: string; options: Record<string, string> }
      ports?: string[]
    }
  >
}

const JIB_LABELS = (app: string) => ({ 'jib.app': app, 'jib.managed': 'true' })
const LOG_OPTS = { driver: 'json-file', options: { 'max-size': '50m', 'max-file': '3' } }

/**
 * Build the jib-managed override structure for a set of discovered services.
 * Pure function — no disk access — so it's trivial to unit test. Returned
 * shape is informational; `writeOverride` serialises via a yaml `Document`
 * so it can stamp the `!override` tag on the `ports:` sequence.
 */
export function buildOverride(app: string, services: OverrideService[]): OverrideFile {
  const out: OverrideFile['services'] = {}
  for (const s of services) {
    out[s.name] = {
      labels: JIB_LABELS(app),
      restart: 'unless-stopped',
      logging: LOG_OPTS,
      ...(s.ports && s.ports.length > 0
        ? { ports: s.ports.map((p) => `${p.host}:${p.container}`) }
        : {}),
    }
  }
  return { services: out }
}

/** Deterministic on-disk path for an app's generated override file. */
export function overridePath(overrideDir: string, app: string): string {
  return join(overrideDir, `${app}.yml`)
}

/**
 * Build a yaml `Document` and stamp `!override` on every service's `ports:`
 * sequence. Compose 2.24+ treats that tag as a list-replacement marker
 * instead of merging with the user's compose file.
 */
export function renderOverrideYAML(app: string, services: OverrideService[]): string {
  const doc = new Document(buildOverride(app, services))
  for (const s of services) {
    if (!s.ports || s.ports.length === 0) continue
    const seq = doc.getIn(['services', s.name, 'ports'], true)
    if (seq instanceof YAMLSeq) {
      seq.tag = '!override'
      for (const item of seq.items) {
        if (item instanceof Scalar) item.type = Scalar.QUOTE_DOUBLE
      }
    }
  }
  return doc.toString()
}

/**
 * Render the override structure to YAML with the jib header comment and
 * write it to `<overrideDir>/<app>.yml`. Returns the absolute path.
 */
export async function writeOverride(
  overrideDir: string,
  app: string,
  services: OverrideService[],
): Promise<string> {
  const yaml = renderOverrideYAML(app, services)
  const header = '# Auto-generated by jib — do not edit\n'
  await mkdir(overrideDir, { recursive: true, mode: 0o750 })
  const outPath = overridePath(overrideDir, app)
  await writeFile(outPath, header + yaml, { mode: 0o640 })
  return outPath
}
