import { describe, expect, test } from 'bun:test'
import { chmodSync, mkdtempSync, readFileSync, writeFileSync } from 'node:fs'
import { tmpdir } from 'node:os'
import { join } from 'node:path'
import { parse as parseYaml } from 'yaml'
import {
  type OverrideService,
  buildOverride,
  overridePath,
  renderOverrideYAML,
  writeOverride,
} from './override.ts'

const bare = (name: string): OverrideService => ({ name })

describe('buildOverride', () => {
  test('returns jib-managed labels, restart, and log rotation per service', () => {
    const out = buildOverride('demo', [bare('web'), bare('worker')])
    expect(Object.keys(out.services)).toEqual(['web', 'worker'])
    const web = out.services.web
    expect(web?.labels).toEqual({ 'jib.app': 'demo', 'jib.managed': 'true' })
    expect(web?.restart).toBe('unless-stopped')
    expect(web?.logging.driver).toBe('json-file')
    expect(web?.logging.options).toEqual({ 'max-size': '50m', 'max-file': '3' })
    expect(web?.ports).toBeUndefined()
  })

  test('emits ports list when service has port mappings', () => {
    const out = buildOverride('demo', [{ name: 'web', ports: [{ host: 20000, container: 80 }] }])
    expect(out.services.web?.ports).toEqual(['20000:80'])
  })
})

describe('renderOverrideYAML', () => {
  test('single-domain app emits !override ports for one service', () => {
    const yaml = renderOverrideYAML('demo', [
      { name: 'web', ports: [{ host: 20000, container: 80 }] },
    ])
    expect(yaml).toContain('ports: !override')
    expect(yaml).toContain('"20000:80"')
  })

  test('multi-domain single-service: one !override block with all entries', () => {
    const yaml = renderOverrideYAML('demo', [
      {
        name: 'web',
        ports: [
          { host: 20000, container: 80 },
          { host: 20001, container: 443 },
        ],
      },
    ])
    const occurrences = yaml.match(/ports: !override/g) ?? []
    expect(occurrences).toHaveLength(1)
    expect(yaml).toContain('"20000:80"')
    expect(yaml).toContain('"20001:443"')
  })

  test('multi-domain multi-service: each service gets its own !override', () => {
    const yaml = renderOverrideYAML('demo', [
      { name: 'web', ports: [{ host: 20000, container: 80 }] },
      { name: 'api', ports: [{ host: 20001, container: 3000 }] },
    ])
    const occurrences = yaml.match(/ports: !override/g) ?? []
    expect(occurrences).toHaveLength(2)
  })

  test('no domains: no ports key emitted at all', () => {
    const yaml = renderOverrideYAML('demo', [bare('web')])
    expect(yaml).not.toContain('ports:')
  })
})

describe('overridePath', () => {
  test('joins app name with .yml extension', () => {
    expect(overridePath('/opt/jib/overrides', 'demo')).toBe('/opt/jib/overrides/demo.yml')
  })
})

describe('writeOverride', () => {
  test('writes valid YAML with jib header and round-trips', async () => {
    const dir = mkdtempSync(join(tmpdir(), 'jib-override-'))
    const path = await writeOverride(dir, 'demo', [bare('web')])
    const raw = readFileSync(path, 'utf8')
    expect(raw).toMatch(/^# Auto-generated by jib/)
    const parsed = parseYaml(raw) as {
      services: Record<string, { labels: Record<string, string> }>
    }
    expect(parsed.services.web?.labels['jib.app']).toBe('demo')
  })

  test('replaces an existing read-only override file atomically', async () => {
    const dir = mkdtempSync(join(tmpdir(), 'jib-override-'))
    const path = overridePath(dir, 'demo')
    writeFileSync(path, '# stale\nservices: {}\n', { mode: 0o400 })
    chmodSync(path, 0o400)

    await writeOverride(dir, 'demo', [bare('web')])

    const raw = readFileSync(path, 'utf8')
    expect(raw).toMatch(/^# Auto-generated by jib/)
    expect(raw).toContain('web:')
  })
})
