package proxy

import "text/template"

const nginxConfTemplate = `# {{ .Filename }} — generated by jib, do not edit
server {
    listen 80;
    server_name {{ .Domain }};
{{ if not .IsTunnel }}
    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
    }
{{ end }}{{ if .HasSSL }}
    location / {
        return 301 https://$host$request_uri;
    }
{{ else }}
    location / {
        proxy_pass http://127.0.0.1:{{ .Port }};
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
{{ end }}}
{{ if .HasSSL }}
server {
    listen 443 ssl;
    server_name {{ .Domain }};

    ssl_certificate     /etc/letsencrypt/live/{{ .Domain }}/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/{{ .Domain }}/privkey.pem;

    add_header Strict-Transport-Security "max-age=31536000; includeSubDomains" always;
    add_header X-Frame-Options "SAMEORIGIN" always;
    add_header X-Content-Type-Options "nosniff" always;
{{ if .NginxInclude }}
    include {{ .NginxInclude }};
{{ end }}{{ if gt .WebhookPort 0 }}
    location = /_jib/webhook {
        proxy_pass http://127.0.0.1:{{ .WebhookPort }};
    }
{{ end }}
    location / {
        proxy_pass http://127.0.0.1:{{ .Port }};
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}
{{ end }}`

const maintenanceConfTemplate = `# {{ .Domain }}.conf — maintenance mode, generated by jib
server {
    listen 80;
    server_name {{ .Domain }};

    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
    }

    root {{ .HTMLDir }};
    error_page 503 /maintenance.html;

    location = /maintenance.html {
        internal;
    }

    location / {
        return 503;
    }
}
{{ if .HasSSL }}
server {
    listen 443 ssl;
    server_name {{ .Domain }};

    ssl_certificate     /etc/letsencrypt/live/{{ .Domain }}/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/{{ .Domain }}/privkey.pem;

    root {{ .HTMLDir }};
    error_page 503 /maintenance.html;

    location = /maintenance.html {
        internal;
    }

    location / {
        return 503;
    }
}
{{ end }}`

const maintenanceHTMLTemplate = `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>Maintenance</title>
<style>
  body { font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif;
         display: flex; align-items: center; justify-content: center;
         min-height: 100vh; margin: 0; background: #f5f5f5; color: #333; }
  .box { text-align: center; padding: 2rem; }
  h1 { font-size: 1.5rem; margin-bottom: 0.5rem; }
  p  { color: #666; }
</style>
</head>
<body>
<div class="box">
  <h1>{{MESSAGE}}</h1>
  <p>Please check back shortly.</p>
</div>
</body>
</html>`

type maintenanceData struct {
	Domain  string
	HTMLDir string
	HasSSL  bool
}

var nginxTmpl *template.Template
var maintenanceTmpl *template.Template

func init() {
	nginxTmpl = template.Must(template.New("nginx").Parse(nginxConfTemplate))
	maintenanceTmpl = template.Must(template.New("maintenance").Parse(maintenanceConfTemplate))
}
