package proxy

import "text/template"

const nginxConfTemplate = `# {{ .Filename }} — generated by jib, do not edit
server {
    listen 80;
    server_name {{ .Domain }};
{{ if not .IsTunnel }}
    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
    }
{{ end }}{{ if .HasSSL }}
    location / {
        return 301 https://$host$request_uri;
    }
{{ else }}
    location / {
        proxy_pass http://127.0.0.1:{{ .Port }};
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
{{ end }}}
{{ if .HasSSL }}
server {
    listen 443 ssl;
    server_name {{ .Domain }};

    ssl_certificate     /etc/letsencrypt/live/{{ .Domain }}/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/{{ .Domain }}/privkey.pem;

    add_header Strict-Transport-Security "max-age=31536000; includeSubDomains" always;
    add_header X-Frame-Options "SAMEORIGIN" always;
    add_header X-Content-Type-Options "nosniff" always;

    location / {
        proxy_pass http://127.0.0.1:{{ .Port }};
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}
{{ end }}`

var nginxTmpl *template.Template

func init() {
	nginxTmpl = template.Must(template.New("nginx").Parse(nginxConfTemplate))
}
