import { describe, expect, test } from 'bun:test'
import { mkdtempSync, readFileSync } from 'node:fs'
import { tmpdir } from 'node:os'
import { join } from 'node:path'
import { parse as parseYaml } from 'yaml'
import { buildOverride, overridePath, writeOverride } from './override.ts'

describe('buildOverride', () => {
  test('returns jib-managed labels, restart, and log rotation per service', () => {
    const out = buildOverride('demo', ['web', 'worker'])
    expect(Object.keys(out.services)).toEqual(['web', 'worker'])
    const web = out.services.web
    expect(web?.labels).toEqual({ 'jib.app': 'demo', 'jib.managed': 'true' })
    expect(web?.restart).toBe('unless-stopped')
    expect(web?.logging.driver).toBe('json-file')
    expect(web?.logging.options).toEqual({ 'max-size': '50m', 'max-file': '3' })
  })
})

describe('overridePath', () => {
  test('joins app name with .yml extension', () => {
    expect(overridePath('/opt/jib/overrides', 'demo')).toBe('/opt/jib/overrides/demo.yml')
  })
})

describe('writeOverride', () => {
  test('writes valid YAML with jib header and round-trips', async () => {
    const dir = mkdtempSync(join(tmpdir(), 'jib-override-'))
    const path = await writeOverride(dir, 'demo', ['web'])
    const raw = readFileSync(path, 'utf8')
    expect(raw).toMatch(/^# Auto-generated by jib/)
    const parsed = parseYaml(raw) as {
      services: Record<string, { labels: Record<string, string> }>
    }
    expect(parsed.services.web?.labels['jib.app']).toBe('demo')
  })
})
