import { mkdir, writeFile } from 'node:fs/promises'
import { join } from 'node:path'
import { stringify as yamlStringify } from 'yaml'

interface ServiceOverride {
  labels: Record<string, string>
  restart: string
  logging: {
    driver: string
    options: Record<string, string>
  }
}

export interface OverrideFile {
  services: Record<string, ServiceOverride>
}

/**
 * Build the jib-managed override structure for a set of discovered services.
 * Pure function — no disk access — so it's trivial to unit test.
 *
 * TODO(future): also publish `<hostPort>:<containerPort>` per domain so
 * nginx can reach `127.0.0.1:<hostPort>`. Today the compose file itself is
 * expected to publish the port; jib's port allocator hands out a host port
 * to the nginx operator but nothing threads it through the generated
 * override. This is a design tension, not a mechanical fix:
 *
 *   - If the user's compose file pins a host port (e.g. `ports: ["8080:80"]`)
 *     then jib's allocator picks, say, 20000, tells nginx to proxy
 *     `127.0.0.1:20000`, and nginx hits nothing because the container is on
 *     8080. Broken v0 for any compose file that publishes ports.
 *   - Forcing `buildOverride` to emit a `ports:` entry would *silently*
 *     shadow whatever the user wrote, which is a different footgun.
 *   - The clean resolution is probably: stop publishing in user compose
 *     files, let jib own the host port end-to-end, and infer
 *     `containerPort` (today hardcoded to 80 in `src/commands/add.ts`)
 *     from the service's `EXPOSE` or the compose `expose:` key.
 *
 * Scoped to a dedicated deployer pass; needs a product decision before
 * code. Tracked alongside the add-command TODO in `src/commands/add.ts`.
 */
export function buildOverride(app: string, services: string[]): OverrideFile {
  const svcOverride: ServiceOverride = {
    labels: { 'jib.app': app, 'jib.managed': 'true' },
    restart: 'unless-stopped',
    logging: {
      driver: 'json-file',
      options: { 'max-size': '50m', 'max-file': '3' },
    },
  }
  const entries = services.map((s) => [s, svcOverride] as const)
  return { services: Object.fromEntries(entries) }
}

/** Deterministic on-disk path for an app's generated override file. */
export function overridePath(overrideDir: string, app: string): string {
  return join(overrideDir, `${app}.yml`)
}

/**
 * Render the override structure to YAML with the jib header comment and
 * write it to `<overrideDir>/<app>.yml`. Returns the absolute path.
 */
export async function writeOverride(
  overrideDir: string,
  app: string,
  services: string[],
): Promise<string> {
  const override = buildOverride(app, services)
  const yaml = yamlStringify(override)
  const header = '# Auto-generated by jib — do not edit\n'
  await mkdir(overrideDir, { recursive: true, mode: 0o750 })
  const outPath = overridePath(overrideDir, app)
  await writeFile(outPath, header + yaml, { mode: 0o600 })
  return outPath
}
