import { mkdir, writeFile } from 'node:fs/promises'
import { join } from 'node:path'
import { stringify as yamlStringify } from 'yaml'

interface ServiceOverride {
  labels: Record<string, string>
  restart: string
  logging: {
    driver: string
    options: Record<string, string>
  }
}

export interface OverrideFile {
  services: Record<string, ServiceOverride>
}

/**
 * Build the jib-managed override structure for a set of discovered services.
 * Pure function — no disk access — so it's trivial to unit test.
 */
export function buildOverride(app: string, services: string[]): OverrideFile {
  const svcOverride: ServiceOverride = {
    labels: { 'jib.app': app, 'jib.managed': 'true' },
    restart: 'unless-stopped',
    logging: {
      driver: 'json-file',
      options: { 'max-size': '50m', 'max-file': '3' },
    },
  }
  const entries = services.map((s) => [s, svcOverride] as const)
  return { services: Object.fromEntries(entries) }
}

/** Deterministic on-disk path for an app's generated override file. */
export function overridePath(overrideDir: string, app: string): string {
  return join(overrideDir, `${app}.yml`)
}

/**
 * Render the override structure to YAML with the jib header comment and
 * write it to `<overrideDir>/<app>.yml`. Returns the absolute path.
 */
export async function writeOverride(
  overrideDir: string,
  app: string,
  services: string[],
): Promise<string> {
  const override = buildOverride(app, services)
  const yaml = yamlStringify(override)
  const header = '# Auto-generated by jib — do not edit\n'
  await mkdir(overrideDir, { recursive: true, mode: 0o750 })
  const outPath = overridePath(overrideDir, app)
  await writeFile(outPath, header + yaml, { mode: 0o600 })
  return outPath
}
