package docker

import (
	"bufio"
	"fmt"
	"net"
	"os"
	"path/filepath"
	"strconv"
	"strings"
)

// GenerateComposeForDockerfile creates a minimal docker-compose.yml in the
// overrides directory for repos that have only a Dockerfile.
// hostPort is the port nginx will proxy to. containerPort is parsed from
// the Dockerfile's EXPOSE directive (defaults to 3000).
// Returns the path to the generated file and the host port used.
func GenerateComposeForDockerfile(app, repoDir, overrideDir string, hostPort int) (string, int, error) {
	containerPort := ParseExposeFromDockerfile(repoDir)
	if containerPort == 0 {
		containerPort = 3000 // sensible default for web apps
	}

	if hostPort == 0 {
		hostPort = findFreePort()
	}

	content := fmt.Sprintf(`# Auto-generated by jib for Dockerfile-only repo
services:
  app:
    build:
      context: %s
    ports:
      - "%d:%d"
`, repoDir, hostPort, containerPort)

	if err := os.MkdirAll(overrideDir, 0o750); err != nil {
		return "", 0, fmt.Errorf("creating override directory: %w", err)
	}

	outPath := filepath.Join(overrideDir, app+"-compose.yml")
	if err := os.WriteFile(outPath, []byte(content), 0o600); err != nil {
		return "", 0, fmt.Errorf("writing generated compose: %w", err)
	}

	return outPath, hostPort, nil
}

// findFreePort asks the OS for an available port.
func findFreePort() int {
	l, err := net.Listen("tcp", "127.0.0.1:0")
	if err != nil {
		return 8080 // fallback
	}
	port := l.Addr().(*net.TCPAddr).Port
	_ = l.Close()
	return port
}

// NeedsGeneratedCompose returns true if the repo has no docker-compose.yml
// but has a Dockerfile.
func NeedsGeneratedCompose(repoDir string, composeFiles []string) bool {
	if len(composeFiles) == 0 {
		composeFiles = []string{"docker-compose.yml"}
	}
	for _, f := range composeFiles {
		path := f
		if !filepath.IsAbs(path) {
			path = filepath.Join(repoDir, path)
		}
		if _, err := os.Stat(path); err == nil {
			return false // compose file exists
		}
	}
	// Check for Dockerfile
	_, err := os.Stat(filepath.Join(repoDir, "Dockerfile"))
	return err == nil
}

// ParseExposeFromDockerfile reads the first EXPOSE directive from a Dockerfile.
func ParseExposeFromDockerfile(repoDir string) int {
	f, err := os.Open(filepath.Join(repoDir, "Dockerfile")) //nolint:gosec // path from trusted repo directory
	if err != nil {
		return 0
	}
	defer func() { _ = f.Close() }()

	scanner := bufio.NewScanner(f)
	for scanner.Scan() {
		line := strings.TrimSpace(scanner.Text())
		if strings.HasPrefix(strings.ToUpper(line), "EXPOSE ") {
			parts := strings.Fields(line)
			if len(parts) >= 2 {
				// Handle "EXPOSE 3000" or "EXPOSE 3000/tcp"
				portStr := strings.Split(parts[1], "/")[0]
				if port, err := strconv.Atoi(portStr); err == nil {
					return port
				}
			}
		}
	}
	return 0
}
