package docker

import (
	"context"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"strings"

	"gopkg.in/yaml.v3"
)

const (
	// DefaultOverrideDir is the default directory for generated override files.
	DefaultOverrideDir = "/opt/jib/overrides"
)

// serviceOverride defines the jib-managed settings applied per service.
type serviceOverride struct {
	Labels  map[string]string `yaml:"labels"`
	Restart string            `yaml:"restart"`
	Logging *loggingConfig    `yaml:"logging"`
}

type loggingConfig struct {
	Driver  string            `yaml:"driver"`
	Options map[string]string `yaml:"options"`
}

type overrideFile struct {
	Services map[string]serviceOverride `yaml:"services"`
}

// GenerateOverride creates an override file at <overrideDir>/<app>.yml with
// jib-managed labels, restart policies, and log rotation for each service.
// It parses the user's compose file(s) to discover service names.
// The override file lives outside the repo to avoid git conflicts.
func GenerateOverride(ctx context.Context, app string, composeFiles []string, repoDir string, overrideDir string) (string, error) {
	services, err := discoverServices(ctx, composeFiles, repoDir)
	if err != nil {
		return "", fmt.Errorf("discovering services: %w", err)
	}

	override := overrideFile{
		Services: make(map[string]serviceOverride, len(services)),
	}

	for _, svc := range services {
		so := serviceOverride{
			Labels: map[string]string{
				"jib.app":     app,
				"jib.managed": "true",
			},
			Restart: "unless-stopped",
			Logging: &loggingConfig{
				Driver: "json-file",
				Options: map[string]string{
					"max-size": "50m",
					"max-file": "3",
				},
			},
		}

		override.Services[svc] = so
	}

	data, err := yaml.Marshal(override)
	if err != nil {
		return "", fmt.Errorf("marshaling override: %w", err)
	}

	if err := os.MkdirAll(overrideDir, 0o750); err != nil {
		return "", fmt.Errorf("creating override directory: %w", err)
	}

	outPath := OverridePath(overrideDir, app)
	header := []byte("# Auto-generated by jib — do not edit\n")
	if err := os.WriteFile(outPath, append(header, data...), 0o600); err != nil {
		return "", fmt.Errorf("writing override file: %w", err)
	}

	return outPath, nil
}

// OverridePath returns the path to the override file for an app.
func OverridePath(overrideDir, app string) string {
	return filepath.Join(overrideDir, app+".yml")
}

// discoverServices parses compose files to extract service names.
func discoverServices(ctx context.Context, composeFiles []string, dir string) ([]string, error) {
	args := []string{"compose"}
	for _, f := range composeFiles {
		args = append(args, "-f", f)
	}
	args = append(args, "config", "--services")

	cmd := exec.CommandContext(ctx, "docker", args...) //nolint:gosec // trusted CLI subprocess
	cmd.Dir = dir
	out, err := cmd.CombinedOutput()
	if err != nil {
		// Fallback: try parsing the YAML directly
		return discoverServicesFromYAML(composeFiles, dir)
	}

	var services []string
	for _, line := range strings.Split(strings.TrimSpace(string(out)), "\n") {
		line = strings.TrimSpace(line)
		if line != "" {
			services = append(services, line)
		}
	}
	return services, nil
}

// discoverServicesFromYAML is a fallback that reads compose files directly
// when docker compose config is not available.
func discoverServicesFromYAML(composeFiles []string, dir string) ([]string, error) {
	if len(composeFiles) == 0 {
		composeFiles = []string{"docker-compose.yml"}
	}

	seen := make(map[string]bool)
	for _, f := range composeFiles {
		path := f
		if !filepath.IsAbs(path) {
			path = filepath.Join(dir, path)
		}
		data, err := os.ReadFile(path) //nolint:gosec // path from trusted compose file list
		if err != nil {
			continue
		}
		var parsed struct {
			Services map[string]interface{} `yaml:"services"`
		}
		if err := yaml.Unmarshal(data, &parsed); err != nil {
			continue
		}
		for name := range parsed.Services {
			seen[name] = true
		}
	}

	services := make([]string, 0, len(seen))
	for name := range seen {
		services = append(services, name)
	}
	return services, nil
}
