package docker

import (
	"context"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"strings"

	"github.com/hexnickk/jib/internal/config"
	"gopkg.in/yaml.v3"
)

const (
	overrideFileName = "override.yml"
	// DefaultOverrideDir is the default directory for generated override files.
	DefaultOverrideDir = "/opt/jib/overrides"
)

// serviceOverride defines the jib-managed settings applied per service.
type serviceOverride struct {
	Labels  map[string]string `yaml:"labels"`
	Restart string            `yaml:"restart"`
	Logging *loggingConfig    `yaml:"logging"`
	Deploy  *deployConfig     `yaml:"deploy,omitempty"`
}

type loggingConfig struct {
	Driver  string            `yaml:"driver"`
	Options map[string]string `yaml:"options"`
}

type deployConfig struct {
	Resources *resourcesConfig `yaml:"resources,omitempty"`
}

type resourcesConfig struct {
	Limits *resourceLimits `yaml:"limits,omitempty"`
}

type resourceLimits struct {
	Memory string `yaml:"memory,omitempty"`
	CPUs   string `yaml:"cpus,omitempty"`
}

type overrideFile struct {
	Services map[string]serviceOverride `yaml:"services"`
}

// GenerateOverride creates an override file at <overrideDir>/<app>.yml with
// jib-managed labels, restart policies, log rotation, and resource limits for each service.
// It parses the user's compose file(s) to discover service names.
// The override file lives outside the repo to avoid git conflicts.
// If resources is non-nil, deploy resource limits are included for every service.
func GenerateOverride(ctx context.Context, app string, composeFiles []string, repoDir string, overrideDir string, resources *config.Resources) (string, error) {
	services, err := discoverServices(ctx, composeFiles, repoDir)
	if err != nil {
		return "", fmt.Errorf("discovering services: %w", err)
	}

	override := overrideFile{
		Services: make(map[string]serviceOverride, len(services)),
	}

	for _, svc := range services {
		so := serviceOverride{
			Labels: map[string]string{
				"jib.app":     app,
				"jib.managed": "true",
			},
			Restart: "unless-stopped",
			Logging: &loggingConfig{
				Driver: "json-file",
				Options: map[string]string{
					"max-size": "50m",
					"max-file": "3",
				},
			},
		}

		if resources != nil && (resources.Memory != "" || resources.CPUs != "") {
			so.Deploy = &deployConfig{
				Resources: &resourcesConfig{
					Limits: &resourceLimits{
						Memory: resources.Memory,
						CPUs:   resources.CPUs,
					},
				},
			}
		}

		override.Services[svc] = so
	}

	data, err := yaml.Marshal(override)
	if err != nil {
		return "", fmt.Errorf("marshaling override: %w", err)
	}

	if err := os.MkdirAll(overrideDir, 0755); err != nil {
		return "", fmt.Errorf("creating override directory: %w", err)
	}

	outPath := OverridePath(overrideDir, app)
	header := []byte("# Auto-generated by jib — do not edit\n")
	if err := os.WriteFile(outPath, append(header, data...), 0644); err != nil {
		return "", fmt.Errorf("writing override file: %w", err)
	}

	return outPath, nil
}

// OverridePath returns the path to the override file for an app.
func OverridePath(overrideDir, app string) string {
	return filepath.Join(overrideDir, app+".yml")
}

// discoverServices parses compose files to extract service names.
func discoverServices(ctx context.Context, composeFiles []string, dir string) ([]string, error) {
	args := []string{"compose"}
	for _, f := range composeFiles {
		args = append(args, "-f", f)
	}
	args = append(args, "config", "--services")

	cmd := exec.CommandContext(ctx, "docker", args...)
	cmd.Dir = dir
	out, err := cmd.CombinedOutput()
	if err != nil {
		// Fallback: try parsing the YAML directly
		return discoverServicesFromYAML(composeFiles, dir)
	}

	var services []string
	for _, line := range strings.Split(strings.TrimSpace(string(out)), "\n") {
		line = strings.TrimSpace(line)
		if line != "" {
			services = append(services, line)
		}
	}
	return services, nil
}

// discoverServicesFromYAML is a fallback that reads compose files directly
// when docker compose config is not available.
func discoverServicesFromYAML(composeFiles []string, dir string) ([]string, error) {
	if len(composeFiles) == 0 {
		composeFiles = []string{"docker-compose.yml"}
	}

	seen := make(map[string]bool)
	for _, f := range composeFiles {
		path := f
		if !filepath.IsAbs(path) {
			path = filepath.Join(dir, path)
		}
		data, err := os.ReadFile(path)
		if err != nil {
			continue
		}
		var parsed struct {
			Services map[string]interface{} `yaml:"services"`
		}
		if err := yaml.Unmarshal(data, &parsed); err != nil {
			continue
		}
		for name := range parsed.Services {
			seen[name] = true
		}
	}

	services := make([]string, 0, len(seen))
	for name := range seen {
		services = append(services, name)
	}
	return services, nil
}
