package docker

import (
	"context"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"strings"

	"gopkg.in/yaml.v3"
)

const overrideFileName = ".jib-compose.yml"

// serviceOverride defines the jib-managed settings applied per service.
type serviceOverride struct {
	Labels  map[string]string `yaml:"labels"`
	Restart string            `yaml:"restart"`
	Logging *loggingConfig    `yaml:"logging"`
}

type loggingConfig struct {
	Driver  string            `yaml:"driver"`
	Options map[string]string `yaml:"options"`
}

type overrideFile struct {
	Services map[string]serviceOverride `yaml:"services"`
}

// GenerateOverride creates .jib-compose.yml in the repo directory with
// jib-managed labels, restart policies, and log rotation for each service.
// It parses the user's compose file(s) to discover service names.
func GenerateOverride(ctx context.Context, app string, composeFiles []string, dir string) (string, error) {
	services, err := discoverServices(ctx, composeFiles, dir)
	if err != nil {
		return "", fmt.Errorf("discovering services: %w", err)
	}

	override := overrideFile{
		Services: make(map[string]serviceOverride, len(services)),
	}

	for _, svc := range services {
		override.Services[svc] = serviceOverride{
			Labels: map[string]string{
				"jib.app":     app,
				"jib.managed": "true",
			},
			Restart: "unless-stopped",
			Logging: &loggingConfig{
				Driver: "json-file",
				Options: map[string]string{
					"max-size": "50m",
					"max-file": "3",
				},
			},
		}
	}

	data, err := yaml.Marshal(override)
	if err != nil {
		return "", fmt.Errorf("marshaling override: %w", err)
	}

	outPath := filepath.Join(dir, overrideFileName)
	header := []byte("# Auto-generated by jib — do not edit\n")
	if err := os.WriteFile(outPath, append(header, data...), 0644); err != nil {
		return "", fmt.Errorf("writing override file: %w", err)
	}

	return outPath, nil
}

// OverridePath returns the path to the override file in a repo directory.
func OverridePath(dir string) string {
	return filepath.Join(dir, overrideFileName)
}

// discoverServices parses compose files to extract service names.
func discoverServices(ctx context.Context, composeFiles []string, dir string) ([]string, error) {
	args := []string{"compose"}
	for _, f := range composeFiles {
		args = append(args, "-f", f)
	}
	args = append(args, "config", "--services")

	cmd := exec.CommandContext(ctx, "docker", args...)
	cmd.Dir = dir
	out, err := cmd.CombinedOutput()
	if err != nil {
		// Fallback: try parsing the YAML directly
		return discoverServicesFromYAML(composeFiles, dir)
	}

	var services []string
	for _, line := range strings.Split(strings.TrimSpace(string(out)), "\n") {
		line = strings.TrimSpace(line)
		if line != "" {
			services = append(services, line)
		}
	}
	return services, nil
}

// discoverServicesFromYAML is a fallback that reads compose files directly
// when docker compose config is not available.
func discoverServicesFromYAML(composeFiles []string, dir string) ([]string, error) {
	if len(composeFiles) == 0 {
		composeFiles = []string{"docker-compose.yml"}
	}

	seen := make(map[string]bool)
	for _, f := range composeFiles {
		path := f
		if !filepath.IsAbs(path) {
			path = filepath.Join(dir, path)
		}
		data, err := os.ReadFile(path)
		if err != nil {
			continue
		}
		var parsed struct {
			Services map[string]interface{} `yaml:"services"`
		}
		if err := yaml.Unmarshal(data, &parsed); err != nil {
			continue
		}
		for name := range parsed.Services {
			seen[name] = true
		}
	}

	services := make([]string, 0, len(seen))
	for name := range seen {
		services = append(services, name)
	}
	return services, nil
}
