/**
 * Pure nginx config generators. Each function takes a typed input and
 * returns a string — no file I/O, no nginx calls. That keeps templates
 * trivial to unit-test and lets hooks.ts own all side effects.
 */

export interface SiteInput {
  host: string
  /** Upstream port on 127.0.0.1. */
  port: number
  /**
   * When `true`, the generated config is for a cloudflare-tunnel backend:
   * skip the ACME challenge block (the domain isn't public-facing) and
   * never emit TLS (the tunnel terminates TLS at Cloudflare's edge).
   */
  isTunnel: boolean
  /**
   * When `true`, also emit a `server { listen 443 ssl; ... }` block using
   * Let's Encrypt cert paths. Caller is responsible for deciding whether
   * certs exist; this function only renders the template.
   */
  hasSSL: boolean
}

/** Renders a complete `<host>.conf` file (HTTP + optional HTTPS block). */
export function renderSite(input: SiteInput): string {
  // Tunnel backends terminate TLS at Cloudflare's edge, so we never emit
  // a 443 server block for them — even if the caller passed `hasSSL: true`.
  const effective: SiteInput = input.isTunnel ? { ...input, hasSSL: false } : input
  const header = `# ${effective.host}.conf — generated by jib, do not edit\n`
  return header + httpServer(effective) + (effective.hasSSL ? httpsServer(effective) : '')
}

function proxyLocation(port: number): string {
  return `    location / {
        proxy_pass http://127.0.0.1:${port};
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
`
}

function httpServer(input: SiteInput): string {
  const acme = input.isTunnel
    ? ''
    : `
    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
    }
`
  const body = input.hasSSL
    ? `
    location / {
        return 301 https://$host$request_uri;
    }
`
    : `\n${proxyLocation(input.port)}`
  return `server {
    listen 80;
    server_name ${input.host};
${acme}${body}}
`
}

function httpsServer(input: SiteInput): string {
  return `
server {
    listen 443 ssl;
    server_name ${input.host};

    ssl_certificate     /etc/letsencrypt/live/${input.host}/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/${input.host}/privkey.pem;

    add_header Strict-Transport-Security "max-age=31536000; includeSubDomains" always;
    add_header X-Frame-Options "SAMEORIGIN" always;
    add_header X-Content-Type-Options "nosniff" always;

${proxyLocation(input.port)}}
`
}

/** Filename nginx uses inside `$JIB_ROOT/nginx/`. */
export function confFilename(host: string): string {
  return `${host}.conf`
}

/**
 * Per-app subdirectory inside `$JIB_ROOT/nginx/`. The nginx operator writes
 * every site config for `app` under `${nginxDir}/${app}/<host>.conf` so
 * `cmd.nginx.release {app}` can remove every file belonging to an app by
 * deleting a single directory. A subdir (rather than a `<app>-` filename
 * prefix) avoids the collision where `app = 'foo'` would match files
 * belonging to `app = 'foo-bar'`.
 */
export function appConfDir(nginxDir: string, app: string): string {
  return `${nginxDir}/${app}`
}

export interface SystemdUnitVars {
  jibRoot: string
  binPath: string
}

/**
 * Systemd unit for the long-running nginx operator. Requires `jib-bus` so the
 * bus is up before the operator tries to connect. Honors `$JIB_ROOT` via an
 * explicit `Environment=` line rather than hard-coding `/opt/jib`.
 */
export function renderSystemdUnit(vars: SystemdUnitVars): string {
  return `[Unit]
Description=jib nginx operator
Requires=jib-bus.service
After=jib-bus.service

[Service]
Type=simple
Environment=JIB_ROOT=${vars.jibRoot}
ExecStart=${vars.binPath} service start nginx
Restart=always
RestartSec=5

[Install]
WantedBy=multi-user.target
`
}

export const NGINX_UNIT_PATH = '/etc/systemd/system/jib-nginx.service'
export const NGINX_SERVICE_NAME = 'jib-nginx.service'
