/**
 * Pure nginx config generators. Each function takes a typed input and
 * returns a string — no file I/O, no nginx calls. That keeps templates
 * trivial to unit-test and lets hooks.ts own all side effects.
 */

export interface SiteInput {
  host: string
  /** Upstream port on 127.0.0.1. */
  port: number
  /**
   * When `true`, the generated config is for a cloudflare-tunnel backend:
   * skip the ACME challenge block (the domain isn't public-facing) and
   * never emit TLS (the tunnel terminates TLS at Cloudflare's edge).
   */
  isTunnel: boolean
  /**
   * When `true`, also emit a `server { listen 443 ssl; ... }` block using
   * Let's Encrypt cert paths. Caller is responsible for deciding whether
   * certs exist; this function only renders the template.
   */
  hasSSL: boolean
}

/** Renders a complete `<host>.conf` file (HTTP + optional HTTPS block). */
export function renderSite(input: SiteInput): string {
  // Tunnel backends terminate TLS at Cloudflare's edge, so we never emit
  // a 443 server block for them — even if the caller passed `hasSSL: true`.
  const effective: SiteInput = input.isTunnel ? { ...input, hasSSL: false } : input
  const header = `# ${effective.host}.conf — generated by jib, do not edit\n`
  return header + httpServer(effective) + (effective.hasSSL ? httpsServer(effective) : '')
}

function proxyLocation(port: number): string {
  return `    location / {
        proxy_pass http://127.0.0.1:${port};
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
`
}

function httpServer(input: SiteInput): string {
  const acme = input.isTunnel
    ? ''
    : `
    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
    }
`
  const body = input.hasSSL
    ? `
    location / {
        return 301 https://$host$request_uri;
    }
`
    : `\n${proxyLocation(input.port)}`
  return `server {
    listen 80;
    server_name ${input.host};
${acme}${body}}
`
}

function httpsServer(input: SiteInput): string {
  return `
server {
    listen 443 ssl;
    server_name ${input.host};

    ssl_certificate     /etc/letsencrypt/live/${input.host}/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/${input.host}/privkey.pem;

    add_header Strict-Transport-Security "max-age=31536000; includeSubDomains" always;
    add_header X-Frame-Options "SAMEORIGIN" always;
    add_header X-Content-Type-Options "nosniff" always;

${proxyLocation(input.port)}}
`
}

/** Filename nginx uses inside `$JIB_ROOT/nginx/`. */
export function confFilename(host: string): string {
  return `${host}.conf`
}
