// Package stack manages the jib service stack (Docker Compose for NATS + service containers).
package stack

import (
	"context"
	"crypto/rand"
	"encoding/hex"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"strings"

	"github.com/hexnickk/jib/internal/config"
)

const (
	// StackDir is the directory for the service stack compose file.
	StackDir = "/opt/jib/stack"
	// ComposeFile is the compose file name within StackDir.
	ComposeFile = "docker-compose.yml"
	// NATSConfFile is the NATS config file name within StackDir.
	NATSConfFile = "nats.conf"
	// ProjectName is the Docker Compose project name.
	ProjectName = "jib-stack"
	// NetworkName is the Docker network shared between stack and app services.
	NetworkName = "jib-net"
)

// composePath returns the full path to the stack compose file.
func composePath() string {
	return filepath.Join(StackDir, ComposeFile)
}

// natsConfPath returns the full path to the NATS config file.
func natsConfPath() string {
	return filepath.Join(StackDir, NATSConfFile)
}

// Tokens holds the NATS auth tokens for different service roles.
type Tokens struct {
	Daemon   string `json:"daemon"`
	Trigger  string `json:"trigger"`
	Monitor  string `json:"monitor"`
	Notifier string `json:"notifier"`
}

// GenerateTokens creates random auth tokens for each role.
func GenerateTokens() (*Tokens, error) {
	gen := func() (string, error) {
		b := make([]byte, 16)
		if _, err := rand.Read(b); err != nil {
			return "", err
		}
		return hex.EncodeToString(b), nil
	}

	t := &Tokens{}
	var err error
	if t.Daemon, err = gen(); err != nil {
		return nil, err
	}
	if t.Trigger, err = gen(); err != nil {
		return nil, err
	}
	if t.Monitor, err = gen(); err != nil {
		return nil, err
	}
	if t.Notifier, err = gen(); err != nil {
		return nil, err
	}
	return t, nil
}

// GenerateNATSConf writes a NATS config file with token-based auth.
func GenerateNATSConf(tokens *Tokens) string {
	return fmt.Sprintf(`# Generated by jib — do not edit
authorization {
  users = [
    {user: "daemon",   password: "%s"}
    {user: "trigger",  password: "%s"}
    {user: "monitor",  password: "%s"}
    {user: "notifier", password: "%s"}
  ]
}
`, tokens.Daemon, tokens.Trigger, tokens.Monitor, tokens.Notifier)
}

// RepoRoot is the path to the jib source repo, used for building service images.
// Set by the CLI before calling EnsureStack.
var RepoRoot = "/opt/jib/src"

// GenerateCompose creates the Docker Compose YAML for the jib service stack.
// It reads the config to determine which services to include.
func GenerateCompose(cfg *config.Config, tokens *Tokens) string {
	var b strings.Builder

	fmt.Fprintf(&b, "# Generated by jib — do not edit\nname: %s\n\nservices:\n", ProjectName)

	// NATS (always).
	fmt.Fprintf(&b, `  jib-bus:
    image: nats:alpine
    restart: unless-stopped
    ports:
      - "127.0.0.1:4222:4222"
    volumes:
      - %s:/etc/nats/nats.conf:ro
    command: ["-c", "/etc/nats/nats.conf"]
    networks:
      - %s
`, natsConfPath(), NetworkName)

	sharedEnv := func(user, pass string) string {
		return fmt.Sprintf(`    environment:
      JIB_CONFIG: /opt/jib/config.yml
      JIB_SECRETS: /opt/jib/secrets
      NATS_URL: nats://jib-bus:4222
      NATS_USER: %s
      NATS_PASS: %s`, user, pass)
	}

	sharedVolumes := `    volumes:
      - /opt/jib/config.yml:/opt/jib/config.yml:ro
      - /opt/jib/secrets:/opt/jib/secrets:ro`

	// Webhook trigger.
	if cfg.Webhook != nil && cfg.Webhook.Enabled {
		port := cfg.Webhook.Port
		if port == 0 {
			port = 9090
		}
		fmt.Fprintf(&b, `
  jib-webhook:
    build:
      context: %s
      dockerfile: services/jib-webhook/Dockerfile
    restart: unless-stopped
    ports:
      - "127.0.0.1:%d:%d"
%s
%s
    networks:
      - %s
`, RepoRoot, port, 9090, sharedEnv("trigger", tokens.Trigger), sharedVolumes, NetworkName)
	}

	// Health monitor (if any app has health checks).
	hasHealth := false
	for _, app := range cfg.Apps {
		if len(app.Health) > 0 {
			hasHealth = true
			break
		}
	}
	if hasHealth {
		fmt.Fprintf(&b, `
  jib-health:
    build:
      context: %s
      dockerfile: services/jib-health/Dockerfile
    restart: unless-stopped
    network_mode: host
%s
%s
`, RepoRoot, sharedEnv("monitor", tokens.Monitor), sharedVolumes)
	}

	// Cert watcher (if certbot is configured and any domain needs certs).
	if cfg.CertbotEmail != "" {
		fmt.Fprintf(&b, `
  jib-certs:
    build:
      context: %s
      dockerfile: services/jib-certs/Dockerfile
    restart: unless-stopped
%s
%s
    networks:
      - %s
`, RepoRoot, sharedEnv("monitor", tokens.Monitor), sharedVolumes, NetworkName)
	}

	// Per-driver notifiers.
	drivers := make(map[string]bool) // track which drivers are needed
	for _, ch := range cfg.Notifications {
		drivers[ch.Driver] = true
	}
	for driver := range drivers {
		svcName := "jib-notify-" + driver
		fmt.Fprintf(&b, `
  %s:
    build:
      context: %s
      dockerfile: services/%s/Dockerfile
    restart: unless-stopped
%s
%s
    networks:
      - %s
`, svcName, RepoRoot, svcName, sharedEnv("notifier", tokens.Notifier), sharedVolumes, NetworkName)
	}

	// Cloudflare tunnel.
	if cfg.Tunnel != nil && cfg.Tunnel.Provider == "cloudflare" && cfg.Tunnel.TunnelID != "" {
		fmt.Fprintf(&b, `
  cloudflared:
    image: cloudflare/cloudflared:latest
    restart: unless-stopped
    network_mode: host
    command: ["tunnel", "run"]
    environment:
      TUNNEL_TOKEN: "${CF_TUNNEL_TOKEN}"
`)
	}

	// Tailscale.
	if cfg.Tunnel != nil && cfg.Tunnel.Provider == "tailscale" {
		fmt.Fprintf(&b, `
  tailscale:
    image: tailscale/tailscale:latest
    restart: unless-stopped
    network_mode: host
    cap_add:
      - NET_ADMIN
      - NET_RAW
    devices:
      - /dev/net/tun:/dev/net/tun
    volumes:
      - /opt/jib/tailscale:/var/lib/tailscale
    environment:
      TS_STATE_DIR: /var/lib/tailscale
      TS_AUTHKEY: "${TS_AUTHKEY}"
`)
	}

	// Network.
	fmt.Fprintf(&b, `
networks:
  %s:
    name: %s
    driver: bridge
`, NetworkName, NetworkName)

	return b.String()
}

// EnsureStack writes the compose and NATS config files, creates directories.
func EnsureStack(cfg *config.Config, tokens *Tokens) error {
	if err := os.MkdirAll(StackDir, 0o750); err != nil { //nolint:gosec // stack dir needs group read for docker
		return fmt.Errorf("creating stack dir: %w", err)
	}

	// Write NATS config
	natsConf := GenerateNATSConf(tokens)
	if err := os.WriteFile(natsConfPath(), []byte(natsConf), 0o600); err != nil {
		return fmt.Errorf("writing NATS config: %w", err)
	}

	// Write compose file
	compose := GenerateCompose(cfg, tokens)
	if err := os.WriteFile(composePath(), []byte(compose), 0o644); err != nil { //nolint:gosec // compose file needs to be readable
		return fmt.Errorf("writing compose file: %w", err)
	}

	return nil
}

// Up starts the stack services.
func Up(ctx context.Context) error {
	return composeCmd(ctx, "up", "-d", "--remove-orphans").Run()
}

// Down stops the stack services.
func Down(ctx context.Context) error {
	return composeCmd(ctx, "down").Run()
}

// Status returns the output of docker compose ps for the stack.
func Status(ctx context.Context) (string, error) {
	cmd := composeCmdQuiet(ctx, "ps", "--format", "table")
	out, err := cmd.Output()
	if err != nil {
		return "", fmt.Errorf("stack status: %w", err)
	}
	return strings.TrimSpace(string(out)), nil
}

// composeCmd returns a docker compose command with stdout/stderr attached to the terminal.
func composeCmd(ctx context.Context, args ...string) *exec.Cmd {
	cmd := composeCmdQuiet(ctx, args...)
	cmd.Stdout = os.Stdout
	cmd.Stderr = os.Stderr
	return cmd
}

// composeCmdQuiet returns a docker compose command without stdout/stderr attached.
func composeCmdQuiet(ctx context.Context, args ...string) *exec.Cmd {
	base := []string{"compose", "-f", composePath(), "-p", ProjectName}
	return exec.CommandContext(ctx, "docker", append(base, args...)...) //nolint:gosec // args from trusted internal values
}
