// Package stack manages the jib service stack (Docker Compose for NATS + service containers).
package stack

import (
	"context"
	"crypto/rand"
	"encoding/hex"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
)

const (
	// StackDir is the directory for the service stack compose file.
	StackDir = "/opt/jib/stack"
	// ComposeFile is the compose file name within StackDir.
	ComposeFile = "docker-compose.yml"
	// NATSConfFile is the NATS config file name within StackDir.
	NATSConfFile = "nats.conf"
	// ProjectName is the Docker Compose project name.
	ProjectName = "jib-stack"
	// NetworkName is the Docker network shared between stack and app services.
	NetworkName = "jib-net"
)

// composePath returns the full path to the stack compose file.
func composePath() string {
	return filepath.Join(StackDir, ComposeFile)
}

// natsConfPath returns the full path to the NATS config file.
func natsConfPath() string {
	return filepath.Join(StackDir, NATSConfFile)
}

// Tokens holds the NATS auth tokens for different service roles.
type Tokens struct {
	Daemon   string `json:"daemon"`
	Trigger  string `json:"trigger"`
	Monitor  string `json:"monitor"`
	Notifier string `json:"notifier"`
}

// GenerateTokens creates random auth tokens for each role.
func GenerateTokens() (*Tokens, error) {
	gen := func() (string, error) {
		b := make([]byte, 16)
		if _, err := rand.Read(b); err != nil {
			return "", err
		}
		return hex.EncodeToString(b), nil
	}

	t := &Tokens{}
	var err error
	if t.Daemon, err = gen(); err != nil {
		return nil, err
	}
	if t.Trigger, err = gen(); err != nil {
		return nil, err
	}
	if t.Monitor, err = gen(); err != nil {
		return nil, err
	}
	if t.Notifier, err = gen(); err != nil {
		return nil, err
	}
	return t, nil
}

// GenerateNATSConf writes a NATS config file with token-based auth.
func GenerateNATSConf(tokens *Tokens) string {
	return fmt.Sprintf(`# Generated by jib — do not edit
authorization {
  users = [
    {user: "daemon",   password: "%s"}
    {user: "trigger",  password: "%s"}
    {user: "monitor",  password: "%s"}
    {user: "notifier", password: "%s"}
  ]
}
`, tokens.Daemon, tokens.Trigger, tokens.Monitor, tokens.Notifier)
}

// GenerateCompose creates the Docker Compose YAML for the jib service stack.
// Currently includes only NATS. Future stages add webhook, health, notifier containers.
func GenerateCompose() string {
	return fmt.Sprintf(`# Generated by jib — do not edit
name: %s

services:
  jib-bus:
    image: nats:alpine
    restart: unless-stopped
    ports:
      - "127.0.0.1:4222:4222"
    volumes:
      - %s:/etc/nats/nats.conf:ro
    command: ["-c", "/etc/nats/nats.conf"]
    networks:
      - %s

networks:
  %s:
    name: %s
    driver: bridge
`, ProjectName, natsConfPath(), NetworkName, NetworkName, NetworkName)
}

// EnsureStack writes the compose and NATS config files, creates directories.
func EnsureStack(tokens *Tokens) error {
	if err := os.MkdirAll(StackDir, 0o750); err != nil { //nolint:gosec // stack dir needs group read for docker
		return fmt.Errorf("creating stack dir: %w", err)
	}

	// Write NATS config
	natsConf := GenerateNATSConf(tokens)
	if err := os.WriteFile(natsConfPath(), []byte(natsConf), 0o600); err != nil {
		return fmt.Errorf("writing NATS config: %w", err)
	}

	// Write compose file
	compose := GenerateCompose()
	if err := os.WriteFile(composePath(), []byte(compose), 0o644); err != nil { //nolint:gosec // compose file needs to be readable
		return fmt.Errorf("writing compose file: %w", err)
	}

	return nil
}

// Up starts the stack services.
func Up(ctx context.Context) error {
	return composeCmd(ctx, "up", "-d", "--remove-orphans").Run()
}

// Down stops the stack services.
func Down(ctx context.Context) error {
	return composeCmd(ctx, "down").Run()
}

// Status returns the output of docker compose ps for the stack.
func Status(ctx context.Context) (string, error) {
	cmd := composeCmdQuiet(ctx, "ps", "--format", "table")
	out, err := cmd.Output()
	if err != nil {
		return "", fmt.Errorf("stack status: %w", err)
	}
	return strings.TrimSpace(string(out)), nil
}

// composeCmd returns a docker compose command with stdout/stderr attached to the terminal.
func composeCmd(ctx context.Context, args ...string) *exec.Cmd {
	cmd := composeCmdQuiet(ctx, args...)
	cmd.Stdout = os.Stdout
	cmd.Stderr = os.Stderr
	return cmd
}

// composeCmdQuiet returns a docker compose command without stdout/stderr attached.
func composeCmdQuiet(ctx context.Context, args ...string) *exec.Cmd {
	base := []string{"compose", "-f", composePath(), "-p", ProjectName}
	return exec.CommandContext(ctx, "docker", append(base, args...)...) //nolint:gosec // args from trusted internal values
}
